### ISSUE TITLE
json-api v1.0 rc2

### ISSUE THREAD

**Issue by csantero** [SphtKr/JSONAPI.NET#54]
@SphtKr Assuming https://github.com/json-api/json-api/pull/341 gets merged in a similar form to where it is now, which seems likely, how do you want to proceed? I'd like to start working on implementing the new spec asap, but I want to make sure you and I are on the same page. Should we set up individual github issues to track each of the changes we need to make to align with rc2?

Also, I think we should cut a release branch for 0.3.0 so we can do the new spec work on master.

**Comment by SphtKr** [comment]
I'm good with targeting the new spec changes with 0.4.0, no question. Yes, we should probably break up some of the major changes into separate issues, because not necessarily all of them will make 0.4.0.

I'm tempted to keep master at 0.3.0 for now just to make us (mainly me) finish the thing. Just gotta get those doc comments in and do some wiki pages.

I had a target of opportunity come up at work, and I'm trying to update an older app to add a feature--but I'm rolling in 0.3.0 at least, so getting some lessons learned, which is a very good thing (how I found #52). But I need to get some of those docs done.

Lets do a branch for 0.4.0, and If you can rebase #51 I think that'll be the last 0.3.0 fix that is not doc-related, so we can probably start doing PRs that will target 0.4.0. It'll be easier I think to merge that back into master once 0.3.0 is released.

**Comment by SphtKr** [comment]
Obviously this being the case I'll target the doc comments for very near-term completion, since this could (hopefully not) cause conflicts, where wiki pages won't.

**Comment by SphtKr** [comment]
Created [0-4-0](/SphtKr/JSONAPI.NET/tree/0-4-0)

**Comment by csantero** [comment]
I'll start adding issues for some of the points in the rc2 PR. I don't expect too much too change between now and when it gets merged. Most likely the only changes will be stuff moving between the main spec and recommendations.
